[K12] K12 Warning Message on Education History
SalesforceFoundation/k12-architecture-kit pull request #274
Opened 2020-09-14 18:25 UTC by m-kinkade

# Critical Changes

# Changes

# Issues Closed
Closes #271 

# New Metadata

# Deleted Metadata

# Testing Notes

2020-09-15 15:51 UTC, juliesnow approved these changes
added a link to product docs for more info

2020-09-22 19:05 UTC, MatthewBlanski requested changes
There are a number of changes requested. The most salient is handling multiple dependent records and some logic flow changes within the specific methods to reduce the number of loops and query only relevant records.

There are a few specific test pieces to handle as well, but otherwise the code is clean and effective.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c oldGradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c oldGradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Id = fakeGradeEnrollId,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c oldGradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c oldGradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c gradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c oldGradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c newGradeEnroll = gradeEnroll.clone(true);
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +            Grade_Enrollment__c oldGradeEnroll = new Grade_Enrollment__c(Contact__c = testContact.Id,
Please use multiple grade enrollments.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-22 19:05 UTC, MatthewBlanski commented on src/classes/GRER_DataInteg_TEST.cls
> +        } catch (Exception e){
Please catch only for the specific exception type we are expecting.

2020-09-24 04:01 UTC, MatthewBlanski approved these changes
This is much improved and targets relevant records only as well as uses multiple records in its unit tests.

2020-09-25 22:18 UTC, spinkelman commented
Passes QA - Merging
Will Close WI

2020-09-25 22:18 UTC, merged